version: "3"
services:
  redis: 
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
     - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: chrisdascoli
      POSTGRES_DB: slack
  web:
    image: slack-server
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet: